spring.application.name=hello-buddy
server.port=9091
paystack.api.key=sk_test_c84a0f8e4b67a575bbd043d81abf20ef4aef54ba
stripe.api.key=sk_test_51TnMSGQiqRLgEPsewUF3BAIOHfKJutb37EN7fk7PXQyW1yKyeTNdivhGYDtBQxyXKxzZWxwYpUp1fXLYl7QH8CYO00TRu9rBBn
#hello.buddy.url=http://localhost:9091
hello.buddy.url=https://www.hellobuddy.africa
paystack.initialize.url=https://api.paystack.co/transaction/initialize
platform.markup=0.065
south.african.fx=15.3500004

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=your_redis_password_if_any

# Cache Configuration
spring.cache.type=redis
# Set a default Time-To-Live (TTL) for caches (e.g., 10 minutes for FX rates)
spring.cache.redis.time-to-live=600000
# Disable caching null values to prevent pollution
spring.cache.redis.cache-null-values=false
stripe.fixed.fee=0.065
#0.30
stripe.percentage.fee=0.029
strip.minimum.amount=0.065

customer.default.email=jephreycuma@hellobuddy.africa