spring.application.name=hello-buddy
server.port=9091
stripe.api.key=sk_test_51TnMRvHHzApRIw8Sk91v79BFXzqrCrBfEehNW9WjraAlaPHBKvtDCfgltxbhhjtAgkrfQKhurTWRx2WmodTq2pNj00YGSRyIYM
hello.buddy.url=http://localhost:9091
#hello.buddy.url=https://www.hellobuddy.co.za
platform.markup=0.15

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=your_redis_password_if_any

# Cache Configuration
spring.cache.type=redis
# Set a default Time-To-Live (TTL) for caches (e.g., 10 minutes for FX rates)
spring.cache.redis.time-to-live=600000
# Disable caching null values to prevent pollution
spring.cache.redis.cache-null-values=false
stripe.fixed.fee=0.30
stripe.percentage.fee=0.029
strip.minimum.amount=0.50